name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.2
        with:
          stable: 'true'
          go-version: '^1.14'
        id: go

      - name: Check out code
        uses: actions/checkout@v2.3.2

      - name: Test
        run: go test -v

